export const cities = [
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Brasília, Brazil",
  "Salvador, Brazil",
  "Fortaleza, Brazil",
  "Belo Horizonte, Brazil",
  "Curitiba, Brazil",
  "Manaus, Brazil",
  "Recife, Brazil",
  "Porto Alegre, Brazil",
  "New York, USA",
  "Los Angeles, USA",
  "Chicago, USA",
  "Houston, USA",
  "Phoenix, USA",
  "Philadelphia, USA",
  "San Antonio, USA",
  "San Diego, USA",
  "Dallas, USA",
  "San Jose, USA",
  "London, UK",
  "Manchester, UK",
  "Birmingham, UK",
  "Liverpool, UK",
  "Edinburgh, UK",
  "Glasgow, UK",
  "Bristol, UK",
  "Sheffield, UK",
  "Leeds, UK",
  "Newcastle, UK",
  "Paris, France",
  "Marseille, France",
  "Lyon, France",
  "Toulouse, France",
  "Nice, France",
  "Nantes, France",
  "Strasbourg, France",
  "Montpellier, France",
  "Bordeaux, France",
  "Lille, France",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Nagoya, Japan",
  "Sapporo, Japan",
  "Fukuoka, Japan",
  "Kobe, Japan",
  "Kyoto, Japan",
  "Yokohama, Japan",
  "Hiroshima, Japan",
  "Sendai, Japan",
  "Berlin, Germany",
  "Hamburg, Germany",
  "Munich, Germany",
  "Cologne, Germany",
  "Frankfurt, Germany",
  "Stuttgart, Germany",
  "Düsseldorf, Germany",
  "Dortmund, Germany",
  "Essen, Germany",
  "Leipzig, Germany",
  "Moscow, Russia",
  "Saint Petersburg, Russia",
  "Novosibirsk, Russia",
  "Yekaterinburg, Russia",
  "Kazan, Russia",
  "Nizhny Novgorod, Russia",
  "Chelyabinsk, Russia",
  "Samara, Russia",
  "Omsk, Russia",
  "Rostov-on-Don, Russia",
  "Beijing, China",
  "Shanghai, China",
  "Guangzhou, China",
  "Shenzhen, China",
  "Chengdu, China",
  "Chongqing, China",
  "Tianjin, China",
  "Wuhan, China",
  "Hangzhou, China",
  "Xi'an, China",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Gold Coast, Australia",
  "Canberra, Australia",
  "Newcastle, Australia",
  "Wollongong, Australia",
  "Hobart, Australia",
  "Mexico City, Mexico",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "Puebla, Mexico",
  "Tijuana, Mexico",
  "León, Mexico",
  "Ciudad Juárez, Mexico",
  "Chihuahua, Mexico",
  "Mérida, Mexico",
  "Cancún, Mexico",
  "Buenos Aires, Argentina",
  "Córdoba, Argentina",
  "Rosario, Argentina",
  "Mendoza, Argentina",
  "La Plata, Argentina",
  "San Miguel de Tucumán, Argentina",
  "Mar del Plata, Argentina",
  "Salta, Argentina",
  "Santa Fe, Argentina",
  "San Juan, Argentina",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Valencia, Spain",
  "Seville, Spain",
  "Zaragoza, Spain",
  "Málaga, Spain",
  "Murcia, Spain",
  "Palma, Spain",
  "Las Palmas, Spain",
  "Bilbao, Spain",
  "Rome, Italy",
  "Milan, Italy",
  "Naples, Italy",
  "Turin, Italy",
  "Palermo, Italy",
  "Genoa, Italy",
  "Bologna, Italy",
  "Florence, Italy",
  "Venice, Italy",
  "Verona, Italy",
  "Cairo, Egypt",
  "Alexandria, Egypt",
  "Giza, Egypt",
  "Shubra El Kheima, Egypt",
  "Port Said, Egypt",
  "Suez, Egypt",
  "Luxor, Egypt",
  "Aswan, Egypt",
  "Mansoura, Egypt",
  "Tanta, Egypt",
  "Istanbul, Turkey",
  "Ankara, Turkey",
  "Izmir, Turkey",
  "Bursa, Turkey",
  "Adana, Turkey",
  "Gaziantep, Turkey",
  "Konya, Turkey",
  "Antalya, Turkey",
  "Mersin, Turkey",
  "Kayseri, Turkey",
  "Delhi, India",
  "Mumbai, India",
  "Bangalore, India",
  "Hyderabad, India",
  "Chennai, India",
  "Kolkata, India",
  "Ahmedabad, India",
  "Pune, India",
  "Jaipur, India",
  "Surat, India",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Incheon, South Korea",
  "Daegu, South Korea",
  "Daejeon, South Korea",
  "Gwangju, South Korea",
  "Suwon, South Korea",
  "Ulsan, South Korea",
  "Changwon, South Korea",
  "Goyang, South Korea",
];
